# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [16]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [17]:
X = np.random.uniform(0,0.4,3)
x = 0.2
m = X.flat[np.abs(X - x).argmin()]
print(m)

0.2150454210388252


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [18]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [20]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        
        obj = np.asarray(input_array).view(cls)
        # Add the new attribute
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
     
        self.name = getattr(obj, 'name', "")

data = np.array([1, 2, 3, 4, 5])
named_array = NamedArray(data, name="MyArray")

print("Array:", named_array)
print("Name:", named_array.name)


Array: [1 2 3 4 5]
Name: MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [21]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 1. 5. 2. 3. 4. 3. 4. 1. 5.]
[3. 1. 9. 3. 5. 7. 5. 7. 1. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [22]:
X = np.array([10, 20, 30, 40])
I = np.array([0, 1, 0, 1])
F = np.zeros(2)  # Initialize F with zeros, size based on unique values in I

# Accumulate elements of X into F based on indices in I
for x, i in zip(X, I):
    F[i] += x

print(F)


[40. 60.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [30]:
w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
# Note that we should compute 256*256 first.
# Otherwise numpy will only promote F.dtype to 'uint16' and overflow will occur
F = I[..., 0] * (256 * 256) + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))
n

OverflowError: Python integer 65536 out of bounds for uint8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [31]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[45 54 62 29]
 [59 60 45 41]
 [48 51 44 51]]
[[45 54 62 29]
 [59 60 45 41]
 [48 51 44 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [32]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4844764  0.5971935  0.49204498 0.31572555 0.4918503  0.62632802
 0.44042058 0.52241417 0.57338665 0.43560607]
0    0.484476
1    0.597194
2    0.492045
3    0.315726
4    0.491850
5    0.626328
6    0.440421
7    0.522414
8    0.573387
9    0.435606
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [33]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.6392784 , 1.44908899, 0.83443729, 1.18349734, 1.52374484])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [34]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [35]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [36]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [37]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(12, 87) (12, 99) (18, 52) (18, 96) (22, 26) (22, 71) (26, 71) (28, 72)
 (28, 90) (28, 93) (28, 94) (31, 50) (31, 67) (37, 38) (37, 51) (38, 51)
 (38, 58) (38, 61) (43, 50) (43, 99) (50, 67) (50, 99) (52, 96) (58, 61)
 (63, 88) (63, 99) (72, 93) (87, 99) (88, 99) (90, 94)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [38]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [39]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [40]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [41]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.25032479,  0.7821017 , -0.65932152, -0.33249599,  0.96134198,
       -0.88501438,  0.62993635, -0.44496857,  0.84976866, -0.64804398,
       -0.59119601,  0.78255717,  0.78148357, -0.38451527, -0.1300662 ,
        0.507859  , -0.73104358, -0.21142099, -0.36421568,  0.58439466,
       -0.82467831,  0.49568323,  0.36198377,  0.04540635, -0.58928091,
        0.32811052,  0.0177229 ,  0.20972554,  0.30773759,  0.79364775,
       -0.26497495,  0.75493424,  0.97349697, -0.53846418, -0.30968011,
       -0.95918766, -0.61779302, -0.20004838,  0.34589031,  0.56012788,
        0.63445296, -0.48743862, -0.05821185, -0.67947774, -0.8894198 ,
        0.12308583, -0.26847596,  0.34106127,  0.64999395, -0.83248066,
       -0.7867168 ,  0.0799098 , -0.29154273,  0.06063136,  0.76545613,
        0.27064213,  0.12159025,  0.70369803,  0.30054199,  0.02945611,
       -0.43316053, -0.20407886, -0.22120806,  0.65651405, -0.62663616,
       -0.89556633, -0.83938009, -0.57038075,  0.01791524, -0.14

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [42]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.38542429 10.18334138  8.45717549  1.10687754  5.56599946 10.65669404
  7.24577728  2.52884723  0.67962682  3.07383642]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [43]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.3665846   4.27439412  6.14018567 14.09630707  3.25034339 11.12853939
  11.45468673 10.04815725  5.93614162  5.50025662]
 [ 0.37199058 10.32449474  8.20245323  3.6136861   8.44430402  0.48029043
   2.44786265  3.18230586  3.51696485 10.46362106]
 [ 9.68675681  5.23669701  7.13764065 15.36749324  4.27146389 10.63202848
  12.50397685 11.16163875  7.24863934  6.00918773]
 [ 0.12989773  8.62001442  6.58231297  4.23084379  6.41208092  2.19447767
   0.96364393  1.89000754  2.59367755  8.03159154]
 [ 5.28477519  0.92391127  2.77324242 10.85135251  2.47034764 10.28912095
   8.0718195   6.66262151  3.71328928  2.62235254]
 [ 3.08028237  1.04005144  2.72830989  9.16172563  1.73753543 14.23705892
   7.77634104  6.03026259  0.20907329  4.40971868]
 [ 6.29536988  0.02916951  1.94746494 11.39975594  5.70638444  6.85051137
   7.44653979  6.31172929  6.00516717  0.42572975]
 [ 1.47969578  4.39117508  2.69912703  4.24129016  2.20357929 12.13757324
   2.37042693  0.68354762  2.71910553  0.5735857 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [46]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [47]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [48]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [49]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 4]
   [3 4 1]
   [4 2 2]]

  [[0 4 2]
   [4 1 1]
   [2 2 2]]

  [[4 2 0]
   [1 1 2]
   [2 2 3]]

  [[2 0 0]
   [1 2 0]
   [2 3 0]]

  [[0 0 2]
   [2 0 0]
   [3 0 4]]

  [[0 2 3]
   [0 0 1]
   [0 4 4]]

  [[2 3 2]
   [0 1 3]
   [4 4 2]]

  [[3 2 4]
   [1 3 3]
   [4 2 2]]]


 [[[3 4 1]
   [4 2 2]
   [4 0 2]]

  [[4 1 1]
   [2 2 2]
   [0 2 2]]

  [[1 1 2]
   [2 2 3]
   [2 2 3]]

  [[1 2 0]
   [2 3 0]
   [2 3 3]]

  [[2 0 0]
   [3 0 4]
   [3 3 0]]

  [[0 0 1]
   [0 4 4]
   [3 0 0]]

  [[0 1 3]
   [4 4 2]
   [0 0 1]]

  [[1 3 3]
   [4 2 2]
   [0 1 0]]]


 [[[4 2 2]
   [4 0 2]
   [4 4 1]]

  [[2 2 2]
   [0 2 2]
   [4 1 0]]

  [[2 2 3]
   [2 2 3]
   [1 0 3]]

  [[2 3 0]
   [2 3 3]
   [0 3 2]]

  [[3 0 4]
   [3 3 0]
   [3 2 0]]

  [[0 4 4]
   [3 0 0]
   [2 0 0]]

  [[4 4 2]
   [0 0 1]
   [0 0 1]]

  [[4 2 2]
   [0 1 0]
   [0 1 0]]]


 [[[4 0 2]
   [4 4 1]
   [3 0 4]]

  [[0 2 2]
   [4 1 0]
   [0 4 4]]

  [[2 2 3]
   [1 0 3]
   [4 4 3]]

  [[2 3 3]
   [0 3 2]
   [4 3 0]]

  [[3 3 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [50]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 13 13 13 17]
 [13  5  6 14 13]
 [13  6  6 42 15]
 [13 14 42  9 11]
 [17 13 15 11  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [51]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [52]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [53]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [54]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [55]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [56]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


C:\Users\KipkorirPbartuiyotBi\AppData\Local\Temp\ipykernel_8176\3979488781.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [57]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [58]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 0 2]
 [0 1 0]
 [2 1 2]
 [2 4 2]
 [4 3 2]
 [1 4 4]
 [2 3 4]
 [4 0 3]
 [4 0 0]
 [1 0 2]]
[[3 0 2]
 [0 1 0]
 [2 1 2]
 [2 4 2]
 [4 3 2]
 [1 4 4]
 [2 3 4]
 [4 0 3]
 [4 0 0]
 [1 0 2]]
[[3 0 2]
 [0 1 0]
 [2 1 2]
 [2 4 2]
 [4 3 2]
 [1 4 4]
 [2 3 4]
 [4 0 3]
 [4 0 0]
 [1 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [60]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [62]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [63]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[1.12254746e-01, 1.19097978e-01, 2.54420657e-03, 4.80598623e-01,
        1.22804659e-01, 9.06572323e-02, 1.21785151e-04, 2.10139343e-01,
        4.27165884e-01, 4.51102660e-01],
       [1.92135055e-01, 2.03847920e-01, 4.35466012e-03, 8.22591877e-01,
        2.10192269e-01, 1.55168782e-01, 2.08447281e-04, 3.59674182e-01,
        7.31136482e-01, 7.72106633e-01],
       [1.42624707e-01, 1.51319341e-01, 3.23252893e-03, 6.10622177e-01,
        1.56028845e-01, 1.15184093e-01, 1.54733515e-04, 2.66991491e-01,
        5.42733478e-01, 5.73146230e-01],
       [6.64711437e-02, 7.05233327e-02, 1.50654049e-03, 2.84584315e-01,
        7.27182269e-02, 5.36822727e-02, 7.21145301e-05, 1.24433068e-01,
        2.52944359e-01, 2.67118413e-01],
       [1.61671838e-01, 1.71527616e-01, 3.66422414e-03, 6.92169063e-01,
        1.76866062e-01, 1.30566607e-01, 1.75397744e-04, 3.02647459e-01,
        6.15214017e-01, 6.49688307e-01],
       [1.32521591e-01, 1.40600322e-01, 3.00354606e-03, 5.67367492e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [64]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [65]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [66]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.05424523  0.36931639]
