# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [16]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [17]:
np.__version__

'2.1.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [31]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [19]:
x = np.zeros((10,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
x = np.arange(50)
x = x[::-1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
nx = np.nonzero([1,2,0,0,4,0])
print(nx)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
x = np.random.random((3,3,3))
print(x)

[[[0.67051044 0.67330506 0.83505427]
  [0.41184628 0.43621278 0.96296311]
  [0.05395565 0.1632172  0.14242031]]

 [[0.70672834 0.31431604 0.60108958]
  [0.68802893 0.62603762 0.13491679]
  [0.48488551 0.3002398  0.80857756]]

 [[0.37726469 0.47789874 0.17660833]
  [0.98450973 0.35215455 0.03675169]
  [0.18742525 0.13442997 0.69266222]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
X = np.random.random((10,10)) 
Xmin, Xmax = X.min(), X.max() 
print(Xmin, Xmax)

0.005952699775582104 0.9803130717226428


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
X = np.random.random(30) 
m = X.mean() 
print(m) 

0.6330600309451653


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
X = np.ones((10,10)) 
X[1:-1,1:-1] = 0 