# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [41]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [42]:
X = np.ones((5,5))
X = np.pad(X, pad_width=1, mode='constant', constant_values=0)
print(X)

# Using fancy indexing
X[:, [0, -1]] = 0
X[[0, -1], :] = 0
print(X)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [43]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [44]:
X = np.diag(1+np.arange(4),k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
X = np.zeros((8,8),dtype=int)
X[1::2,::2] = 1
X[::2,1::2] = 1
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [46]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [47]:
X = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [48]:
X = np.random.random((5,5))
X = (X - np.mean (X)) / (np.std (X))
print(X)

[[ 0.85840071 -0.99326931 -1.01839344  1.25247528  0.36056571]
 [-1.19171138 -0.78264707  1.30613015  1.3568089  -1.20043503]
 [-0.46150656  1.57850972  1.40436006  0.31742837 -1.27066053]
 [-1.41442341 -0.04466792 -0.62819371 -0.17978868  1.03719875]
 [ 0.1998793   0.44929397  1.07201808 -1.33284754 -0.67452443]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [49]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [50]:
X = np.dot(np.ones((5,3)), np.ones((3,2)))
print(X)

X = np.ones((5,3)) @ np.ones((3,2))
print(X)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
X = np.arange(11)
X[(3 < X) & (X < 8)] *= -1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [52]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [53]:
#Z**Z -  This us legal
#2 << Z >> 2 - Legal Performs bitwise left and right shifts by niner 2
#Z <- Z
#1j*Z - This is legal - multiples each element of z by imaginary j... complex number
#Z/1/1 - Legal - Devides each element of z by 1 twice
#Z<Z>Z - This is not valid Python Operation

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [54]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\KipkorirPbartuiyotBi\AppData\Local\Temp\ipykernel_38956\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\KipkorirPbartuiyotBi\AppData\Local\Temp\ipykernel_38956\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\KipkorirPbartuiyotBi\AppData\Local\Temp\ipykernel_38956\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [55]:
X = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(X)), X))

# More readable but less efficient
print(np.where(X>0, np.ceil(X), np.floor(X)))

[  8.   6.  10.   8.   1.   4.  -9. -10.   2.  -5.]
[  8.   6.  10.   8.   1.   4.  -9. -10.   2.  -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [56]:
X1 = np.random.randint(0,10,10)
X2 = np.random.randint(0,10,10)
print(np.intersect1d(X1,X2))

[3 5 7 8]
